version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: expense_tracker_db
    restart: always
    environment:
      MYSQL_DATABASE: expensetracker
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: expenseuser
      MYSQL_PASSWORD: expensepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
